# Generated by Django 5.2.3 on 2025-06-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_application_status'),
        ('accounts', '0005_employerprofile_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Job.company')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseekerprofile')),
            ],
            options={
                'unique_together': {('company', 'jobseeker')},
            },
        ),
    ]
