# Generated by Django 5.2.3 on 2025-07-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_company_logo_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
