# Generated by Django 5.2.3 on 2025-06-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employerprofile_jobseekerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
